
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ekdkckjfggwivuicxiye.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVrZGtja2pmZ2d3aXZ1aWN4aXllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY4NjY2MzIsImV4cCI6MjA5MjQ0MjYzMn0.ZZeffwTeGmdqa_2l573f3s-6SD7KubotUCxnkk_LYgA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
